name: tahania_app
description: "تطبيق تهنئة للتهاني والرسائل التوعوية"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  firebase_core: ^2.27.0
  firebase_auth: ^4.15.3
  google_sign_in: ^6.1.6
  flutter_signin_button: ^2.0.0
  url_launcher: ^6.2.2
  fl_chart: ^0.65.0
  http: ^1.1.2
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  intl: ^0.19.0
  lottie: ^2.7.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  share_plus: ^7.2.1
  screenshot: ^2.1.0
  crypto: ^3.0.3
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.1
  flutter_contacts: ^1.1.7+1
  permission_handler: ^11.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.1
  flutter_svg: ^2.0.9
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.4.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  flutter_secure_storage: ^9.0.0
  connectivity_plus: ^5.0.2
  package_info_plus: ^8.3.0
  device_info_plus: ^9.1.1
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.13.1
  logger: ^2.0.2+1
  flutter_dotenv: ^5.1.0
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo.png
    - assets/images/onboarding/
    - assets/data/
    - assets/translations/
    - assets/icons/
    - assets/stickers/
    - assets/animations/
    - .env
    - assets/images/google_icon.png

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf

# إعدادات شاشة البداية
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  color_dark: "#121212"
  image_dark: assets/images/logo.png
  
  android_12:
    image: assets/images/logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/logo.png
    icon_background_color_dark: "#121212"

  web: false
  ios: true
  android: true
