name: tahania_app
description: تطبيق تهنئة لإرسال واستقبال التهاني تلقائياً مع دعم العربية.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_localizations:
    sdk: flutter
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png

    - assets/images/onboarding/tahnia1.png
    - assets/images/onboarding/tahnia2.png
    - assets/images/onboarding/tahnia3.png
    - assets/images/onboarding/tahnia4.png

  fonts:
  - family: Cairo
    fonts:
      - asset: assets/fonts/Cairo-Regular.ttf
      - asset: assets/fonts/Cairo-Bold.ttf

