name: tahnia-Genspark
description: A new Flutter project for greeting messages.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # Core dependencies
  shared_preferences: ^2.2.2
  uuid: ^4.1.0
  flutter_contacts: ^1.1.7
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  flutter_cache_manager: ^3.3.1
  cached_network_image: ^3.3.0
  share_plus: ^7.2.1
  screenshot: ^2.1.0
  lottie: ^2.7.0
  sticker_view: ^1.0.0
  flutter_icons: ^1.1.0
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  path_provider: ^2.1.1
  provider: ^6.1.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/stickers/
    - assets/animations/
    - .env